---
title: "Hand on Exercise 3-2"
format: 
  html:
    toc: true
    toc-title: "Table of Contents"
    toc-location: left
    code-fold: show
    code-tools: true
    theme: cosmo
editor: visual
---

this is 3-2

```{r}
pacman::p_load(readxl, gifski, gapminder,
               plotly, gganimate, tidyverse)
```

```{r}
col <- c("Country", "Continent")
globalPop <- read_xls("GlobalPopulation.xls",
                      sheet="Data") %>%
  mutate_at(col, as.factor) %>%
  mutate(Year = as.integer(Year))
```

```{r}
col <- c("Country", "Continent")

globalPop <- read_xls("GlobalPopulation.xls", sheet="Data") %>%
  # Wrap 'col' in all_of() to tell R it's an external list of names
  mutate(across(all_of(col), as.factor)) %>%
  mutate(Year = as.integer(Year))
```

```{r}
ggplot(globalPop, aes(x = Old, y = Young, 
                      size = Population, 
                      colour = Country)) +
  geom_point(alpha = 0.7, 
             show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  labs(title = 'Year: {frame_time}', 
       x = '% Aged', 
       y = '% Young') 
```

```{r}
# Load necessary libraries
pacman::p_load(tidyverse, gganimate, gifski)

# 1. Import Data
raw_data <- read_csv("respopagesextod2025.csv")

# 2. Transform Data
pop_data <- raw_data %>%
  # Define Age Categories
  mutate(Age_Category = case_when(
    AG %in% c("0_to_4", "5_to_9", "10_to_14") ~ "Young",
    AG %in% c("65_to_69", "70_to_74", "75_to_79", "80_to_84", "85_to_89", "90_and_over") ~ "Old",
    TRUE ~ "Working_Age"
  )) %>%
  # Aggregate by Planning Area and Time
  group_by(PA, Time) %>%
  summarise(
    Total_Pop = sum(Pop),
    Young_Pop = sum(Pop[Age_Category == "Young"]),
    Old_Pop = sum(Pop[Age_Category == "Old"]),
    .groups = 'drop'
  ) %>%
  # Filter empty areas and calculate percentages
  filter(Total_Pop > 0) %>%
  mutate(Percent_Young = (Young_Pop / Total_Pop) * 100,
         Percent_Old = (Old_Pop / Total_Pop) * 100)                      
```

```{r}
ggplot(pop_data, aes(x = Percent_Old, y = Percent_Young, 
                     size = Total_Pop, 
                     colour = PA)) +
  geom_point(alpha = 0.7, 
             show.legend = FALSE) +
  scale_size(range = c(2, 12)) +
  labs(title = 'Year: 2025', 
       x = '% Aged', 
       y = '% Young')
# 注意：这里删除了 transition_time 和 ease_aes
```

```{r}
# 1. 确保加载包
pacman::p_load(tidyverse, gganimate, gifski)

# 2. 准备基础数据 (确保你已经运行过之前的 transform 步骤得到了 pop_data)
# 如果没有 pop_data，请先运行之前的数据处理代码！

# 3. 【关键步骤】生成模拟数据：复制一份 2025 的数据，伪装成 2020
pop_data_simulated <- pop_data %>%
  mutate(Time = 2025) %>% # 确保原始数据是 2025
  bind_rows(
    pop_data %>% 
      mutate(Time = 2020, # 伪造一个 2020 年
             # 让点的位置稍微移动一下，这样动画能看出来在动
             Percent_Old = Percent_Old * 0.9,  
             Percent_Young = Percent_Young * 1.1)
  )

# 4. 绘图（使用 pop_data_simulated）
ggplot(pop_data_simulated, aes(x = Percent_Old, y = Percent_Young, 
                               size = Total_Pop, 
                               colour = PA)) +
  geom_point(alpha = 0.7, 
             show.legend = FALSE) +
  scale_size(range = c(2, 12)) +
  labs(title = 'Year: {frame_time}', 
       x = '% Aged', 
       y = '% Young') +
  transition_time(Time) +         
  ease_aes('linear')
```

```{r}
gg <- ggplot(globalPop, 
       aes(x = Old, 
           y = Young, 
           size = Population, 
           colour = Country)) +
  geom_point(aes(size = Population,
                 ),
             alpha = 0.7, 
             show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  labs(x = '% Aged', 
       y = '% Young')

ggplotly(gg)
```

```{r}
gg <- ggplot(globalPop, 
       aes(x = Old, 
           y = Young, 
           size = Population, 
           colour = Country)) +
  geom_point(aes(size = Population,
                 ),
             alpha = 0.7) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  labs(x = '% Aged', 
       y = '% Young') + 
  theme(legend.position='none')

ggplotly(gg)
```

```{r}
bp <- globalPop %>%
  plot_ly(x = ~Old, 
          y = ~Young, 
          size = ~Population, 
          color = ~Continent,
          sizes = c(2, 100),
          frame = ~Year, 
          text = ~Country, 
          hoverinfo = "text",
          type = 'scatter',
          mode = 'markers'
          ) %>%
  layout(showlegend = FALSE)
bp
```
